### PR TITLE
fix bcrypt binary incompatibility

### LINKED ISSUE #6837: Symbol not found in @node-rs/bcrypt when upgrade from 4.2.0 to 4.3.0
We use GitHub Issues for reporting bugs with Parse Server.

Make sure these boxes are checked before submitting your issue - thanks for reporting issues back to Parse Server!

- [x] This isn't a vulnerability disclosure, if it is please follow our [security policy](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).

- [x] You're running version >=2.3.2 of Parse Server, we can't accept issues for very outdated releases, please update to a newer version.

- [x] This isn't a question, if you need if you have questions about code please use Stack Overflow with the [parse-platform tag](https://stackoverflow.com/questions/tagged/parse-platform) & other questions can be posted on the [community forum](https://community.parseplatform.org).

- [x] You've searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue), your issue may have been reported or resolved before.

### Issue Description

Upgrading to `4.3.0` from `4.2.0` causes an error when I run parse server. I get this message:

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/davidyeiser/dev/oombla-app/node_modules/@node-rs/bcrypt/bcrypt.darwin.node
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/davidyeiser/dev/oombla-app/node_modules/@node-rs/bcrypt/bcrypt.darwin.node
  Expected in: /usr/lib/libSystem.B.dylib
```

Perhaps related to https://github.com/parse-community/parse-server/pull/6794

I can't connect to the server at all. When I downgrade to `4.2.0` the error goes away and I can connect like normal. Nothing changes in my codebase, just the version of `parse-server` installed.

### Steps to reproduce

I have a lot of things in my set up, it's mixed with Create React App, etc. I'm not sure how you would reproduce it, I just know that trying to use 4.3.0 causes the error. Some dead-end Google searches mentioned perhaps a binary that was built on a newer version of Mac OS? But I'm really not sure.

Using these packages:

```
"parse": "2.12.0",
"parse-dashboard": "2.0.5",
"parse-server": "4.2.0",
```

My computer is nearly six years old, so that could be the problem :) I'm fine to just use 4.2.0. Feel free to close this if it doesn't seem relevant, wanted to report it just in case.

### Environment Setup

- **Server**
  - parse-server version: 4.3.0
  - Operating System: macOS Sierra 10.12.6
  - Hardware: iMac 27" Retina 5k Late 2014
  - Localhost or remote server? localhost

- **Database**
  - MongoDB version: 3.6.3
  - Storage engine:  WiredTiger (I think?)
  - Hardware: It's running on my computer, same as above, but not sure if that's what this is asking.
  - Localhost or remote server? localhost

### PR DESCRIPTION
**Pull request by mtrezza**
closes #6837

### CODE REVIEW

**Comment by mtrezza** [comment]
@dplewis Aren't packages automatically upgraded by the bots on Github? I am surprised this packages was still on an old version.

**Comment by arlanding** [comment]
Is this already released? I'm using "parse-server": "^4.3.0" and I'm still having this issue. https://github.com/parse-community/parse-server/issues/6837

**Comment by mtrezza** [comment]
The fix has not been released yet. Parse Server 4.3.0 was released on July 19, this PR was merged in September.

**Comment by arlanding** [comment]
got it. Do you have a release date?

**Comment by mtrezza** [comment]
Parse Server has no fixed release cycles, but that is something we will look into to provide more transparency and predictably.

**Comment by arlanding** [comment]
Thanks!! I did what you said and It worked awesome. I'm a forking man now
