### ISSUE TITLE
Cannot find module 'multer'

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#4963]
### Issue Description

When upgrading from parse server 2.8.3 to 2.8.4 on heroku the app crashes with error:
`Error: Cannot find module 'multer'`

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.8.4
  - Operating System:     -
  - Hardware:             -
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): heroku

### Logs/Trace
-

**Comment by flovilmart** [comment]
There should be no need of the multer module anymore, it’s not referenced at all in the parse-server codebase

**Comment by mtrezza** [comment]
My bad, `multer` was referenced outside of parse server, hence the error. Closing.
