### ISSUE TITLE
Symbol not found in @node-rs/bcrypt when upgrade from 4.2.0 to 4.3.0

### ISSUE THREAD

**Issue by davidyeiser** [parse-community/parse-server#6837]
We use GitHub Issues for reporting bugs with Parse Server.

Make sure these boxes are checked before submitting your issue - thanks for reporting issues back to Parse Server!

- [x] This isn't a vulnerability disclosure, if it is please follow our [security policy](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).

- [x] You're running version >=2.3.2 of Parse Server, we can't accept issues for very outdated releases, please update to a newer version.

- [x] This isn't a question, if you need if you have questions about code please use Stack Overflow with the [parse-platform tag](https://stackoverflow.com/questions/tagged/parse-platform) & other questions can be posted on the [community forum](https://community.parseplatform.org).

- [x] You've searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue), your issue may have been reported or resolved before.

### Issue Description

Upgrading to `4.3.0` from `4.2.0` causes an error when I run parse server. I get this message:

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/davidyeiser/dev/oombla-app/node_modules/@node-rs/bcrypt/bcrypt.darwin.node
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/davidyeiser/dev/oombla-app/node_modules/@node-rs/bcrypt/bcrypt.darwin.node
  Expected in: /usr/lib/libSystem.B.dylib
```

Perhaps related to https://github.com/parse-community/parse-server/pull/6794

I can't connect to the server at all. When I downgrade to `4.2.0` the error goes away and I can connect like normal. Nothing changes in my codebase, just the version of `parse-server` installed.

### Steps to reproduce

I have a lot of things in my set up, it's mixed with Create React App, etc. I'm not sure how you would reproduce it, I just know that trying to use 4.3.0 causes the error. Some dead-end Google searches mentioned perhaps a binary that was built on a newer version of Mac OS? But I'm really not sure.

Using these packages:

```
"parse": "2.12.0",
"parse-dashboard": "2.0.5",
"parse-server": "4.2.0",
```

My computer is nearly six years old, so that could be the problem :) I'm fine to just use 4.2.0. Feel free to close this if it doesn't seem relevant, wanted to report it just in case.

### Environment Setup

- **Server**
  - parse-server version: 4.3.0
  - Operating System: macOS Sierra 10.12.6
  - Hardware: iMac 27" Retina 5k Late 2014
  - Localhost or remote server? localhost

- **Database**
  - MongoDB version: 3.6.3
  - Storage engine:  WiredTiger (I think?)
  - Hardware: It's running on my computer, same as above, but not sure if that's what this is asking.
  - Localhost or remote server? localhost

**Comment by mtrezza** [comment]
Thanks for opening this issue. From your description it seems you are running Parse Server locally.

Can you please try the following when upgrading Parse Server:

1. change Parse Server dependency to 4.3.0
1. delete files `package-lock.json`
1. delete folder `node-modules`
1. run `npm install` in the local Parse Server directory
1. run `npm build` in the local Parse Server directory

**Comment by davidyeiser** [comment]
I'll put together a sample repository next week to try to recreate it if I can.

**Comment by davidyeiser** [comment]
I created a test case here: https://github.com/davidyeiser/test-parse-server-express

With Parse Server 4.3.0 I get the following message when I run `npm run dev`:

```
$ npm run dev

> test-parse-server-express@0.1.0 dev <~LOCAL_PATH>/test-parse-server-express
> node api/index.js

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: <~LOCAL_PATH>/test-parse-server-express/node_modules/@node-rs/bcrypt/bcrypt.darwin.node
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: <~LOCAL_PATH>/test-parse-server-express/node_modules/@node-rs/bcrypt/bcrypt.darwin.node
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
$ 
```

If I change `parse-server` to `4.2.0` it works fine: Parse Server loads and I can access Parse Dashboard.

**Comment by mtrezza** [comment]
The error message looks to me as if the prebuilt bcrypt binary was not compatible with your version of macOS.

Can you try to:
1. remove from package.json:
```
"optionalDependencies": {
    "@node-rs/bcrypt": "0.3.0"
  }
```
2. delete file package-lock.json
3. delete folder node_modules
4. run npm install
5. run npm i bcrypt

**Comment by mtrezza** [comment]
Maybe related to https://github.com/parse-community/parse-server/pull/6794

**Comment by Brooooooklyn** [comment]
oh yes，but it supposed to be fixed in 0.4.1. So let's upgrade it?

**Comment by mtrezza** [comment]
@davidyeiser Can you try upgrading to 0.4.1 and see whether it works for you?

**Comment by davidyeiser** [comment]
What would be the best way to do that? In the test repository, you're talking about upgrading the `@node-rs/bcrypt` package in `dependencies` and `optionalDependencies` to `0.4.1` within the `node_modues/parse-server` package, correct?

**Comment by mtrezza** [comment]
Yes, that should work. You would set the version of `@node-rs/bcrypt` to `0.4.1` in package.json and package-lock.json for the `node_modues/parse-server` package.

**Comment by davidyeiser** [comment]
I updated the `node_modules/parse-server/package.json` to point to `0.4.1` for `@node-rs/bcrypt` and ran `npm install` from the project root directory, but that didn't seem to upgrade it. 

Then, from the root directory, I just ran `npm uninstall @node-rs/bcrypt` and then ran `npm install @node-rs/bcrypt` (which installed v. 0.4.1) and then the project worked as expected.

So that seems to fix the problem — thank you!

**Comment by davidyeiser** [comment]
(Ah, I missed the package-lock.json) Let me know if the comment I just posted is sufficient for a test case.

**Comment by mtrezza** [comment]
Yes, I seems we need to upgrade the bcrypt version.

**Comment by mtrezza** [comment]
The PR has been merged in the newest version of Parse Server 4.4.0.
