### ISSUE TITLE
parse-server 3.3.0 breaks on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by acinader** [parse-community/parse-server#5592]
Starting with parse-server@3.3.0, parse-server does not have a `./lib` dir.

Reverting to 3.2.3 solves the problem.

the output from `npm install` in `/var/log/eb-activity.log` looks normal. 

I took a look at: https://github.com/parse-community/parse-server/compare/3.2.3...3.3.0

but nothing is jumping out.  Will need to debug...

```
> glow-cloud@1.0.0 start /var/app/current
> parse-server ./config.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '../lib/cli/parse-server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
```

**Comment by dplewis** [comment]
Is that path correct in that `./config.js`

**Comment by acinader** [comment]
it is.  and it works just fine in 3.2.3.  When I upgrade to 3.3.0 the lib dir doesn't get generated and I don't know why yet.

**Comment by dplewis** [comment]
Does `npm prepare` run? Are you installing from npm or branch?

**Comment by acinader** [comment]
yeah!  when I went back to debug it, I could no longer reproduce.
